services:
  backend:
    build: .
    image: jwt:local
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD_FILE: /run/secrets/pg_password
    volumes:
      - ./secrets/public.pem:/run/secrets/public.pem:ro
      - ./secrets/private.pkcs8.pem:/run/secrets/private.pkcs8.pem:ro
    secrets:
      - pg_password
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:17.6
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    secrets:
      - pg_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:9.8
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
    volumes:
      - pgadmin:/var/lib/pgadmin
    secrets:
      - pgadmin_password
    ports:
      - "5050:80"
    depends_on:
      - database

volumes:
  pgdata:
    external: true
  pgadmin:

secrets:
  pg_password:
    file: ./secrets/pg_password
  pgadmin_password:
    file: ./secrets/pgadmin_password